
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${DB_DLL}

application:
  security:
    jwt:
      secret-key: ${AUTH_SECRET}

  cors:
    allowed-origins: >
      http://localhost:5137