
spring:

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/agentapp}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: ${DB_DLL:create}

application:
  security:
    jwt:
      secret-key: simplesecretkey0simplesecretkey0simplesecretkey0simplesecretkey0

  cors:
    allowed-origins: >
      http://localhost:3000,
      http://localhost:5173,
      http://localhost:8080

api:
  version: 1.0.0
  description: "This API provides endpoints for user management."
  server:
    url: "http://localhost:8080"
  tos:
    uri: "https://www.example.com/terms-of-service"

springdoc:
  api-docs:
    enabled: true